if (NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required.")
endif()

if (NOT DEFINED INCLUDE_ROOT)
    message(FATAL_ERROR "INCLUDE_ROOT is required.")
endif()

set(header_paths "")
if (DEFINED HEADER_PATHS AND NOT HEADER_PATHS STREQUAL "")
    string(REPLACE "||" ";" header_paths "${HEADER_PATHS}")
endif()

set(script_includes "")
set(register_entries "")
set(unregister_entries "")

foreach(script_header_path IN LISTS header_paths)
    file(RELATIVE_PATH script_header "${INCLUDE_ROOT}" "${script_header_path}")

    if (script_header STREQUAL "RegisterScripts.hpp")
        continue()
    endif()

    get_filename_component(script_stem "${script_header}" NAME_WE)
    file(READ "${script_header_path}" script_header_contents)

    if (NOT script_header_contents MATCHES "Register${script_stem}Script[ \t\r\n]*\\(")
        continue()
    endif()

    if (NOT script_header_contents MATCHES "UnRegister${script_stem}Script[ \t\r\n]*\\(")
        continue()
    endif()

    list(APPEND script_includes "#include <${script_header}>")

    get_filename_component(script_dir "${script_header}" DIRECTORY)
    if (script_dir)
        string(REPLACE "/" "::" script_namespace "${script_dir}")
        set(script_prefix "${script_namespace}::")
    else()
        set(script_prefix "")
    endif()

    list(APPEND register_entries "        &${script_prefix}Register${script_stem}Script,")
    list(APPEND unregister_entries "        &${script_prefix}UnRegister${script_stem}Script,")
endforeach()

list(SORT script_includes)
list(SORT register_entries)
list(SORT unregister_entries)

set(script_includes_text "")
foreach(script_include IN LISTS script_includes)
    string(APPEND script_includes_text "${script_include}\n")
endforeach()

set(register_entries_text "")
foreach(register_entry IN LISTS register_entries)
    string(APPEND register_entries_text "${register_entry}\n")
endforeach()

set(unregister_entries_text "")
foreach(unregister_entry IN LISTS unregister_entries)
    string(APPEND unregister_entries_text "${unregister_entry}\n")
endforeach()

set(generated_source
"// This file is generated by CMake. Do not edit by hand.
#include <RegisterScripts.hpp>

#include <Canis/App.hpp>
${script_includes_text}

namespace
{
    using ScriptRegistrar = void (*)(Canis::App &);

    constexpr ScriptRegistrar kRegisterScriptFns[] = {
${register_entries_text}    };

    constexpr ScriptRegistrar kUnRegisterScriptFns[] = {
${unregister_entries_text}    };
}

void RegisterScripts(Canis::App &_app)
{
    for (ScriptRegistrar register_script : kRegisterScriptFns)
        register_script(_app);
}

void UnRegisterScripts(Canis::App &_app)
{
    for (ScriptRegistrar unregister_script : kUnRegisterScriptFns)
        unregister_script(_app);
}
")

if (EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" existing_source)
else()
    set(existing_source "")
endif()

if (NOT existing_source STREQUAL generated_source)
    file(WRITE "${OUTPUT_FILE}" "${generated_source}")
endif()
